### ISSUE TITLE
Detect which browsers are installed on the system and instantiate the corresponding WebDriver

### ISSUE THREAD

**Issue by native-api-work** [atata-framework/atata-webdriversetup#11]
My Selenium-based .NET Windows desktop program will be automating some specific laborous operations with a website that doesn't have a web API.

As such, it will be installed on user machines which may have any combination of browsers installed.

In the README, I see how to install driver(s) for specific installed browsers -- but there seems to be no information on how to detect which browsers are installed on the system in the first place.

I'd like to be able to:
* Probe for installed browsers in a specified order of preference and stop on the first one that is detected
  * The site may only officially support some browsers, so it will be either just those ones, or a few preferred browsers followed by "everything else"
* Install the corresponding selenium driver executable and instantiate the corresponding Selenium `WebDriver` class for whatever was detected, optionally with specific parameters that I prepare beforehand (e.g. for some browsers, I need to install addons to be able to work with the site).

Can I do this with Atata.WebDriverSetup?

**Comment by YevgeniyShunevych** [comment]
Atata.WebDriverSetup is not created for detecting browsers installations. But it can do such a bit, but only for Chrome and Edge. For other browsers there is no such implementations to check browser versions. Here is an example:

```cs
bool isChromeInstalled = new ChromeDriverSetupStrategy(new HttpRequestExecutor())
    .GetInstalledBrowserVersion() != null;

bool isEdgeInstalled = new EdgeDriverSetupStrategy(new HttpRequestExecutor())
    .GetInstalledBrowserVersion() != null;
```

As an alternative approach, instead of checking installed browsers, if machine permissions allow, you can in setup stage install needed browser, using for example `choco install googlechrome` or another way.

**Comment by native-api-work** [comment]
I'm primarily interested in Firefox and Chrome.

So I believe I can contribute version detection logic for Firefox -- and that'll be enough.

Would you be interested in the general detection of a suiteable installed browser as described earlier, too?

**Comment by YevgeniyShunevych** [comment]
Great. Yes, it should be possible to get Firefox version in a way similar to the way it is done for Chrome. If you want to create PR for that, welcome!

> Would you be interested in the general detection of a suitable installed browser as described earlier, too?

Probably, why not. Need to think about public method(s) for that. Please just create it as a separate PR.

**Comment by YevgeniyShunevych** [comment]
The functionality that determines installed Firefox version is implemented.

Additionally, I've implemented a functionality for browser installation detection. The [BrowserDetector](https://github.com/atata-framework/atata-webdriversetup/blob/main/src/Atata.WebDriverSetup/BrowserDetector.cs) class was added for that. Please check whether the provided functionality suits your needs. I'm going to release Atata.WebDriverSetup 2.4.0 on Monday.

### BrowserDetector Usage

#### Get First Installed Browser Name

```cs
string browserName = BrowserDetector.GetFirstInstalledBrowserName(
    BrowserNames.Chrome,
    BrowserNames.Firefox,
    BrowserNames.Edge);
```

#### Is Browser Installed

```cs
bool isChromeInstalled = BrowserDetector.IsBrowserInstalled(BrowserNames.Chrome);
```

#### Get Installed Browser Version

```cs
string chromeVersion = BrowserDetector.GetInstalledBrowserVersion(BrowserNames.Chrome);
```

**Comment by native-api-work** [comment]
From the functionality described above, the detector doesn't detect "everything else" -- but in my case, it's a safe bet to assume that if Chrome and Firefox aren't installed, Edge is (since the workstations would be Win7 and Win10). So it's enough for my needs atm. Thank you!

**Comment by YevgeniyShunevych** [comment]
Great. You are welcome. I've made a release of v2.4.0.
