### ISSUE TITLE
Webdriver can't be downloaded for new chrome ver. 115 and higher.

### ISSUE THREAD

**Issue by dbelykh** [atata-framework/atata-webdriversetup#14]
The following exception is raised when launching tests:
"OneTimeSetUp: System.Net.Http.HttpRequestException : Response status code does not indicate success: 404 (Not Found)."
The AutoSetUpDriverToUse() is called on the OneTimeSetUp step.

The most possible reason is that starting from version 115 Google changed the URLs for webdriver downloading:
https://chromedriver.chromium.org/downloads
https://googlechromelabs.github.io/chrome-for-testing/

1) New base url is https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.98/linux64/chrome-linux64.zip
But Atata.WebDriverSetup tries to get appropriate driver version using old url: https://chromedriver.storage.googleapis.com
2) the URL parameters are also a bit changed.
3) it seems that it is not possible to just get latest release or get webdriver if you don't know the exact driver version.

**Comment by YevgeniyShunevych** [comment]
Thank you @dbelykh for reporting that. I will be taking a look at this issue.

As a temporarily hot fix (before the fix in the library), instead of `AtataContext.GlobalConfiguration.AutoSetUpDriverToUse()` or similar setup code, you can use v114 for now:

```cs
DriverSetup.ConfigureChrome()
    .WithVersion("114.0.5735.90")
    .SetUp();
```

**Comment by dbelykh** [comment]
@YevgeniyShunevych Thank you very much for the advise!)
I also have discovered an alternative workaround:
Put the correct webdriver manually to a directory /drivers/chrome/{version} and modify versioncache.xm
<versions>
  <version browser="{actual browser version}" driver="{actual driver version}" timestamp="{some recent time, eg. 2023-07-19 13:10:21Z}" />
<version browser="latest" driver="{actual driver version}"" timestamp="{some recent time, eg. 2023-07-19 14:10:21Z}"/>
</versions>
Not sure if the last row is required. But maybe it will work even after minor browser update.

**Comment by YevgeniyShunevych** [comment]
I have just released Atata.WebDriverSetup v2.7.0 with added support of Chrome v115+ via Chrome for Testing API endpoints. Please update the version and check it out.

**Comment by dbelykh** [comment]
Thank you for the prompt response. I have updated to 2.7.0. But nothing is changed. Same exception. And folder bin/drivers/chrome is empty.

**Comment by YevgeniyShunevych** [comment]
Strange. I updated on couple of projects and it was OK. May it be because you modified `versioncache.xml` or something else? You can try to completely remove `drivers` folder.

**Comment by dbelykh** [comment]
Yes, I have removed this drivers folder firstly.
I have setup driver code in a separate Nuget package. I have updated it there but haven't updated in the main project.
After updating it there too, the issue is not reproduced anymore.
Thank you a lot for the prompt response and fix :-)

**Comment by YevgeniyShunevych** [comment]
Great. Thanks again for raising this issue.
