### ISSUE TITLE
AtataContextBuilder.AutoSetUpDriverToUse() throws exception when used with the new Chrome version 121.0.6167.185

### ISSUE THREAD

**Issue by dbelykh** [atata-framework/atata-webdriversetup#15]
The issue is emerged after Chrome update to version **121.0.6167.185** (Official Build) (64-bit)

The following error is displayed when test is launched:
"System.IO.InvalidDataException : End of Central Directory record could not be found."

Stack Trace: 
ZipArchive.ReadEndOfCentralDirectory()
ZipArchive.ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
DriverSetupExecutor.ExtractFromZip(String archiveFilePath, String destinationFilePath)
DriverSetupExecutor.ExtractDownloadedFile(String sourceFilePath, String destinationFilePath)
DriverSetupExecutor.DownloadDriverIfMissing(String version, String driverDestinationDirectoryPath, String driverDestinationFileName)
DriverSetupExecutor.SetUp(String version)
DriverSetupConfigurationBuilder.ExecuteSetUp()
DriverSetupConfigurationBuilder.SetUp()
Task`1.InnerInvoke()
ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
DriverSetupConfigurationBuilder.SetUpAsync()
DriverSetup.AutoSetUpAsync(String browserName)
DriverSetup.AutoSetUpAsync(IEnumerable`1 browserNames)
DriverSetup.AutoSetUpSafelyAsync(IEnumerable`1 browserNames)
lambda_method393(Closure)
MethodInfoExtensions.InvokeStaticAsLambda(MethodInfo method, Object[] args)
AtataContextBuilder.InvokeAutoSetUpSafelyMethodOfDriverSetup(IEnumerable`1 browserNames)
AtataContextBuilder.AutoSetUpDriverToUse()

**Comment by dbelykh** [comment]
Currently using driver with the following version can be a workaround:
'''
DriverSetup.ConfigureChrome()
    .WithVersion("121.0.6167.85")
    .SetUp();
'''

**Comment by YevgeniyShunevych** [comment]
Thanks @dbelykh for posting that. I am aware and have already stated with a fix. It will be released soon.

**Comment by YevgeniyShunevych** [comment]
Atata.WebDriverSetup 2.10.0 is released with a fix.

**Comment by dbelykh** [comment]
The fix works. Bug is not reproduced. Thank you!
